import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";

// Load Inter and Poppins fonts
const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '600'],  // Adjust the weights as needed
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600'],  // Adjust the weights as needed
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${poppins.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
